version: '3.3'
services:
  app: 
    build: .
    env_file: 
      - .env
    ports:
      - 8080:8080
    depends_on: 
      - db
  db:
    image: postgres:10.6
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=expenses
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=p@ssword